version: '3.8'

name: 'assessment-open-ai'

services:
  db:
    image: postgres:15-alpine
    container_name: assessment_user_ia
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=assessment_db
    ports:
      - '5432:5432'
    volumes:
      - .data:/var/lib/postgresql/data